# Generated by Django 3.0.8 on 2020-07-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('E', 'Employed'), ('U', 'Unemployed')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
