# Generated by Django 3.0.8 on 2020-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], max_length=100),
        ),
    ]
